# Generated by Django 3.2.9 on 2021-11-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_register_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
