# Generated by Django 3.2.9 on 2021-12-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camnang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camnang',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
