# Generated by Django 3.2.9 on 2021-12-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('hotel_name', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('star', models.PositiveSmallIntegerField(default='')),
                ('nearby', models.CharField(choices=[('B', 'Beach'), ('M', 'Mountain')], default='B', max_length=1)),
                ('map', models.URLField(default='')),
                ('phone', models.IntegerField(default='')),
                ('image', models.ImageField(default=None, upload_to='hotel_img')),
                ('decription', models.TextField(default='')),
                ('like', models.PositiveSmallIntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(default='', max_length=100)),
                ('price', models.PositiveIntegerField(default='')),
                ('valu', models.PositiveSmallIntegerField(default='')),
                ('hotel_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Img_slide',
            fields=[
                ('img_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(default=None, upload_to='slide_hotel_img')),
                ('hotel_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Firnish',
            fields=[
                ('firnish_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('firnish_name', models.CharField(default='', max_length=100)),
                ('hotel_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
